config/routes.rb
Rails.application.routes.draw do

  root 'epicenter#feed'

  get 'user_profile' => 'epicenter#show_user'

  post 'now_following' => 'epicenter#now_following'

  post 'unfollow' => 'epicenter#unfollow'

  resources :tweets
  devise_for :users

 

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    # Create the association between Tweet and User
    # TTS-SLIDE09
	belongs_to :user
  
	# Add validations for the tweets
	# TTS-SLIDE15
	validates :message, presence: true
    validates :message, length: {maximum: 140, too_long: "A tweet is only 140 max. Everybody knows that!"}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Create the association between User and Tweets
  # TTS-SLIDE09 
  has_many :tweets     

  # Add validations for the username
  # TTS-SLIDE15
  validates :username, presence: true
  validates :username, uniqueness: true

  # Make the following attribute an array
  # TTS-SLIDE25
  serialize :following, Array

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Adding security for the columns we just added 
  # TTS-SLIDE07
  before_action :configure_permitted_parameters, if: :devise_controller?

	  protected

	  def configure_permitted_parameters

	    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, 
	      :name, :username, :bio, :location) }

	    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, 
	      :current_password, :name, :username, :bio, :location) }

	  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  def feed
  	# TTS-SLIDE28
    # Create and initialize the array
  	@following_tweets = []

  	# Get all the tweets
  	@tweets = Tweet.all

  	# Sort and find the ones with the current user
  	@tweets.each do |tweet|
  		current_user.following.each do |f|
  			if tweet.user_id  == f
  				@following_tweets.push(tweet)
  			end
  		end
  	end
  end

  def show_user
    # Find the user
    # TTS-SLIDE29
    @user = User.find(params[:id])
  end

  def now_following
      # TTS-SLIDE29
      @user = User.find(params[:follow_id])

      current_user.following.push(params[:follow_id].to_i)

      current_user.save
  end

  def unfollow
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # Do not allow anyone in who isnt authenticated    
  # TTS-SLIDE10
  before_filter :authenticate_user!

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/epicenter/feed.html.erb
<!-- Your greeting page -->
<!-- TTS-SLIDE27 -->

<h1>Your Twitter Feed</h1>
<p>Hello, <%= current_user.name %> !</p>
<p>Here is what your friends are saying:</p>

<div>
 <% @following_tweets.each do |f| %>
   <div> 
   	<p> <%= f.message %> </p>
   	<p><strong><em> <%= f.user.username %> </em></strong></p>
   </div>
</div>
<% end %>   

app/views/epicenter/now_following.html.erb
<p>You are now following: <%= @user.username %> </p>

app/views/epicenter/show_user.html.erb
<!-- Show user page -->
<!--TTS-SLIDE29 -->

<h1><%= @user.username %></h1>
<h3><%= @user.location %></h3>
<h3>Bio:</h3>
<p><%= @user.bio %></p>

<div class="row">
	<% @user.tweets.each do |tweet| %>
	<div class="col-mid-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <p><%= tweet.message %></p>
        </div>
	  </div>
    </div>
    <% end %>
</div>

<div>
  <%= form_tag('/now_following') do %>
    <span class "invisible">
      <%= text_field_tag :follow_id, @user.id %>
    </span> <br />
  <%= submit_tag "Follow", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollo</h1>
<p>Find me in app/views/epicenter/unfollo.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BetterTwitter</title>
	<!-- These are the lines that come from Bootstrap TTS-SLIDE04 -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- TTS-SLIDE12  -->
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <%= link_to "Your Feed", root_path, class: "navbar-brand" %>
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-left">
	      	<li>
	          <%= link_to tweets_path do %>
	            <span class="glyphicon glyphicon-record"></span> All Tweets
	          <% end %>
	        </li>
	        <!-- Future Links! -->
	      </ul>
	      <ul class="nav navbar-nav navbar-right">
	      	<% if user_signed_in? %>
		        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
		        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
	        <% else %>
	        	<li><%= link_to "Sign Up",  new_user_registration_path %></li>
	    		<li><%= link_to "Forgot Password",  new_user_password_path %></li>
	        <% end %>
	      </ul>
	    </div>
	  </div>
	</nav>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- Add the current_user.id so you can pass it -->
  <!-- TTS-SLIDE20  -->
  <div class= "form-group">
    <%= f.text_field :message, class: "form-control" %>
  </div>
  <div class="form-group cant-see-me">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit "Tweet!", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= tweet.user_id %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <!-- Add the username to the form -->
  <!-- TTS-SLIDES22
  <strong>User:</strong>
  <%= @tweet.user.username %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>